package bakpack

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strconv"
	"strings"

	"github.com/martinghunt/bakpack/internal/buildinfo"
)

// BaktaGFF3Options configures Bakta JSON to GFF3 rendering.
type BaktaGFF3Options struct {
	// AnnotationOnly omits the terminal ##FASTA section containing contig
	// sequences.
	AnnotationOnly bool
	// BakpackVersion overrides the version written in the generated-by header.
	// When empty, the build-time bakpack version is used.
	BakpackVersion string
}

// BaktaGFF3 renders a Bakta JSON annotation as GFF3 using the observed Bakta
// JSON/GFF3 file formats. The input may be either original JSON or bakpack
// reduced JSON; reduced input is restored before rendering.
func BaktaGFF3(annotation []byte, genome Genome) ([]byte, error) {
	return BaktaGFF3WithOptions(annotation, genome, BaktaGFF3Options{})
}

// BaktaGFF3WithOptions renders a Bakta JSON annotation as GFF3 with explicit
// output options.
func BaktaGFF3WithOptions(annotation []byte, genome Genome, opts BaktaGFF3Options) ([]byte, error) {
	root, err := DecodeJSON(annotation)
	if err != nil {
		return nil, err
	}
	data, ok := root.(map[string]any)
	if !ok {
		return nil, fmt.Errorf("Bakta JSON root is not an object")
	}
	if _, ok := data[reducedMetadataKey]; ok {
		restored, err := RestoreBaktaJSON(annotation, genome)
		if err != nil {
			return nil, err
		}
		root, err = DecodeJSON(restored.OriginalJSON)
		if err != nil {
			return nil, err
		}
		data, ok = root.(map[string]any)
		if !ok {
			return nil, fmt.Errorf("Bakta JSON root is not an object")
		}
	}
	if err := validateBaktaFeatureTypes(data); err != nil {
		return nil, err
	}

	sequences := gffSequences(data, genome)
	featuresByContig, featureOrder := gffFeaturesByContig(data)

	var buf bytes.Buffer
	writeGFF3Header(&buf, data, opts.bakpackVersion())
	seenContigs := map[string]bool{}
	for _, sequence := range sequences {
		if sequence.ID == "" {
			continue
		}
		seenContigs[sequence.ID] = true
		writeSequenceRegion(&buf, sequence)
		for _, feature := range featuresByContig[sequence.ID] {
			if err := writeGFF3Feature(&buf, feature); err != nil {
				return nil, err
			}
		}
	}
	for _, contig := range featureOrder {
		if seenContigs[contig] {
			continue
		}
		for _, feature := range featuresByContig[contig] {
			if err := writeGFF3Feature(&buf, feature); err != nil {
				return nil, err
			}
		}
	}
	if !opts.AnnotationOnly {
		writeGFF3FASTA(&buf, sequences)
	}
	return buf.Bytes(), nil
}

type gffSequence struct {
	ID       string
	Length   int
	Sequence string
}

func (opts BaktaGFF3Options) bakpackVersion() string {
	if opts.BakpackVersion != "" {
		return opts.BakpackVersion
	}
	return buildinfo.Version
}

func writeGFF3Header(buf *bytes.Buffer, data map[string]any, bakpackVersion string) {
	buf.WriteString("##gff-version 3\n")
	buf.WriteString("##feature-ontology https://github.com/The-Sequence-Ontology/SO-Ontologies/blob/v3.1/so.obo\n")
	fmt.Fprintf(buf, "# Generated by bakpack %s\n", bakpackVersion)
	buf.WriteString("# Annotated with Bakta\n")
	version, _ := data["version"].(map[string]any)
	if baktaVersion, _ := version["bakta"].(string); baktaVersion != "" {
		fmt.Fprintf(buf, "# Software: v%s\n", baktaVersion)
	}
	db, _ := version["db"].(map[string]any)
	dbVersion, _ := db["version"].(string)
	dbType, _ := db["type"].(string)
	if dbVersion != "" || dbType != "" {
		fmt.Fprintf(buf, "# Database: v%s", dbVersion)
		if dbType != "" {
			fmt.Fprintf(buf, ", %s", dbType)
		}
		buf.WriteByte('\n')
	}
	buf.WriteString("# DOI: 10.1099/mgen.0.000685\n")
	buf.WriteString("# URL: github.com/oschwengers/bakta\n")
}

func gffSequences(data map[string]any, genome Genome) []gffSequence {
	var sequences []gffSequence
	for _, entry := range mapSlice(data["sequences"]) {
		id, _ := entry["id"].(string)
		if id == "" {
			continue
		}
		sequence, _ := entry["sequence"].(string)
		length, ok := jsonInt(entry["length"])
		if !ok {
			if sequence != "" {
				length = len(sequence)
			} else if contig, ok := genome.Contig(id); ok {
				length = len(contig)
			}
		}
		if sequence == "" {
			if contig, ok := genome.Contig(id); ok {
				sequence = string(contig)
			}
		}
		sequences = append(sequences, gffSequence{
			ID:       id,
			Length:   length,
			Sequence: strings.ToUpper(sequence),
		})
	}
	if len(sequences) != 0 {
		return sequences
	}
	for _, contig := range genome.Contigs {
		sequences = append(sequences, gffSequence{
			ID:       contig.Name,
			Length:   len(contig.Seq),
			Sequence: string(contig.Seq),
		})
	}
	return sequences
}

func gffFeaturesByContig(data map[string]any) (map[string][]map[string]any, []string) {
	featuresByContig := map[string][]map[string]any{}
	seen := map[string]bool{}
	var order []string
	for _, feature := range mapSlice(data["features"]) {
		contig, _ := feature["contig"].(string)
		if contig == "" {
			contig = "."
		}
		if !seen[contig] {
			seen[contig] = true
			order = append(order, contig)
		}
		featuresByContig[contig] = append(featuresByContig[contig], feature)
	}
	return featuresByContig, order
}

func writeSequenceRegion(buf *bytes.Buffer, sequence gffSequence) {
	fmt.Fprintf(buf, "##sequence-region %s 1 %d\n", sequence.ID, sequence.Length)
	fmt.Fprintf(buf, "%s\tBakta\tregion\t1\t%d\t.\t+\t.\tID=%s;Name=%s\n",
		sequence.ID,
		sequence.Length,
		gffEscape(sequence.ID),
		gffEscape(sequence.ID),
	)
}

func writeGFF3Feature(buf *bytes.Buffer, feature map[string]any) error {
	featureType, _ := feature["type"].(string)
	info, ok := baktaFeatureType(featureType)
	if !ok {
		return unsupportedBaktaFeatureTypeError(featureType)
	}
	if info.CRISPR {
		return writeCRISPRFeature(buf, feature)
	}

	contig, _ := feature["contig"].(string)
	start, startOK := jsonInt(feature["start"])
	stop, stopOK := jsonInt(feature["stop"])
	if contig == "" || !startOK || !stopOK {
		return nil
	}
	score := "."
	if info.Infernal {
		score = gffNumber(feature["evalue"])
	}
	strand, _ := feature["strand"].(string)
	if strand == "" {
		strand = "."
	}
	phase := "."
	if info.GFF3Type == "CDS" {
		phase = "0"
	}
	attrs := gffAttributes(feature)
	fmt.Fprintf(buf, "%s\t%s\t%s\t%d\t%d\t%s\t%s\t%s\t%s\n",
		contig, info.GFF3Source, info.GFF3Type, start, stop, score, strand, phase, attrs)
	return nil
}

func gffAttributes(feature map[string]any) string {
	featureType, _ := feature["type"].(string)
	info, _ := baktaFeatureType(featureType)
	switch info.GFF3Attr {
	case gffAttrKindProtein:
		return gffProteinAttributes(feature)
	case gffAttrKindGap:
		return gffGapAttributes(feature)
	case gffAttrKindOrigin:
		return gffOriginAttributes(feature)
	case gffAttrKindRNA:
		return gffRNAAttributes(feature)
	case gffAttrKindRegulatoryRegion:
		return gffRegulatoryRegionAttributes(feature)
	case gffAttrKindTRNA:
		return gffTRNAAttributes(feature)
	default:
		return gffAttrString([]gffAttr{{Key: "ID", Value: gffFeatureID(feature)}})
	}
}

func gffProteinAttributes(feature map[string]any) string {
	product, _ := feature["product"].(string)
	attrs := []gffAttr{
		{Key: "ID", Value: gffFeatureID(feature)},
		{Key: "Name", Value: product},
	}
	if locus, _ := feature["locus"].(string); locus != "" {
		attrs = append(attrs, gffAttr{Key: "locus_tag", Value: locus})
	}
	attrs = append(attrs, gffAttr{Key: "product", Value: product})
	attrs = appendDBXrefs(attrs, feature)
	if pseudo, _ := feature["pseudo"].(bool); pseudo {
		attrs = append(attrs, gffAttr{Key: "pseudogene", Value: "unitary"})
	}
	if gene, _ := feature["gene"].(string); gene != "" {
		attrs = append(attrs, gffAttr{Key: "gene", Value: gene})
	}
	return gffAttrString(attrs)
}

func gffGapAttributes(feature map[string]any) string {
	length, _ := jsonInt(feature["length"])
	product := fmt.Sprintf("gap (%d bp)", length)
	return gffAttrString([]gffAttr{
		{Key: "ID", Value: gffFeatureID(feature)},
		{Key: "Name", Value: product},
		{Key: "product", Value: product},
	})
}

func gffOriginAttributes(feature map[string]any) string {
	product, _ := feature["product"].(string)
	return gffAttrString([]gffAttr{
		{Key: "ID", Value: gffFeatureID(feature)},
		{Key: "Name", Value: product},
		{Key: "product", Value: product},
		{Key: "inference", Value: "similar to DNA sequence"},
	})
}

func gffRNAAttributes(feature map[string]any) string {
	product, _ := feature["product"].(string)
	attrs := []gffAttr{
		{Key: "ID", Value: gffFeatureID(feature)},
		{Key: "Name", Value: product},
	}
	if locus, _ := feature["locus"].(string); locus != "" {
		attrs = append(attrs, gffAttr{Key: "locus_tag", Value: locus})
	}
	if gene, _ := feature["gene"].(string); gene != "" {
		attrs = append(attrs, gffAttr{Key: "gene", Value: gene})
	}
	attrs = append(attrs, gffAttr{Key: "product", Value: product})
	attrs = appendDBXrefs(attrs, feature)
	if isTruncated(feature) {
		attrs = append(attrs, gffAttr{Key: "pseudo", Value: "True"})
	}
	return gffAttrString(attrs)
}

func gffRegulatoryRegionAttributes(feature map[string]any) string {
	product, _ := feature["product"].(string)
	attrs := []gffAttr{
		{Key: "ID", Value: gffFeatureID(feature)},
		{Key: "Name", Value: product},
		{Key: "product", Value: product},
	}
	attrs = appendDBXrefs(attrs, feature)
	if isTruncated(feature) {
		attrs = append(attrs, gffAttr{Key: "pseudo", Value: "True"})
	}
	return gffAttrString(attrs)
}

func gffTRNAAttributes(feature map[string]any) string {
	product, _ := feature["product"].(string)
	attrs := []gffAttr{
		{Key: "ID", Value: gffFeatureID(feature)},
		{Key: "Name", Value: product},
	}
	if locus, _ := feature["locus"].(string); locus != "" {
		attrs = append(attrs, gffAttr{Key: "locus_tag", Value: locus})
	}
	attrs = append(attrs, gffAttr{Key: "product", Value: product})
	attrs = appendDBXrefs(attrs, feature)
	if gene, _ := feature["gene"].(string); gene != "" {
		attrs = append(attrs, gffAttr{Key: "gene", Value: gene})
	}
	if antiCodon, _ := feature["anti_codon"].(string); antiCodon != "" {
		attrs = append(attrs, gffAttr{Key: "anti_codon", Value: antiCodon})
	}
	if aminoAcid, _ := feature["amino_acid"].(string); aminoAcid != "" {
		attrs = append(attrs, gffAttr{Key: "amino_acid", Value: aminoAcid})
	}
	return gffAttrString(attrs)
}

func writeCRISPRFeature(buf *bytes.Buffer, feature map[string]any) error {
	contig, _ := feature["contig"].(string)
	start, startOK := jsonInt(feature["start"])
	stop, stopOK := jsonInt(feature["stop"])
	if contig == "" || !startOK || !stopOK {
		return nil
	}
	strand, _ := feature["strand"].(string)
	if strand == "" {
		strand = "?"
	}
	id := gffFeatureID(feature)
	product, _ := feature["product"].(string)
	parentAttrs := gffAttrString([]gffAttr{
		{Key: "ID", Value: id},
		{Key: "Name", Value: product},
		{Key: "product", Value: product},
	})
	fmt.Fprintf(buf, "%s\tPILER-CR\tCRISPR\t%d\t%d\t.\t%s\t.\t%s\n",
		contig, start, stop, strand, parentAttrs)

	repeats := mapSlice(feature["repeats"])
	spacers := mapSlice(feature["spacers"])
	count := len(repeats)
	if len(spacers) > count {
		count = len(spacers)
	}
	for i := 0; i < count; i++ {
		if i < len(repeats) {
			writeCRISPRChild(buf, contig, id, strand, "crispr-repeat", fmt.Sprintf("%s_repeat_%d", id, i+1), repeats[i], "")
		}
		if i < len(spacers) {
			sequence, _ := spacers[i]["sequence"].(string)
			writeCRISPRChild(buf, contig, id, strand, "crispr-spacer", fmt.Sprintf("%s_spacer_%d", id, i+1), spacers[i], sequence)
		}
	}
	return nil
}

func writeCRISPRChild(buf *bytes.Buffer, contig, parentID, parentStrand, featureType, id string, child map[string]any, sequence string) {
	start, startOK := jsonInt(child["start"])
	stop, stopOK := jsonInt(child["stop"])
	if !startOK || !stopOK {
		return
	}
	strand, _ := child["strand"].(string)
	if strand == "" {
		strand = parentStrand
	}
	attrs := []gffAttr{
		{Key: "ID", Value: id},
		{Key: "Parent", Value: parentID},
	}
	if sequence != "" {
		attrs = append(attrs, gffAttr{Key: "sequence", Value: sequence})
	}
	fmt.Fprintf(buf, "%s\tPILER-CR\t%s\t%d\t%d\t.\t%s\t.\t%s\n",
		contig, featureType, start, stop, strand, gffAttrString(attrs))
}

func appendDBXrefs(attrs []gffAttr, feature map[string]any) []gffAttr {
	dbxrefs := stringSlice(feature["db_xrefs"])
	if len(dbxrefs) == 0 {
		return attrs
	}
	return append(attrs, gffAttr{Key: "Dbxref", Values: dbxrefs})
}

func gffFeatureID(feature map[string]any) string {
	if locus, _ := feature["locus"].(string); locus != "" {
		return locus
	}
	if id, _ := feature["id"].(string); id != "" {
		return id
	}
	return "."
}

func isTruncated(feature map[string]any) bool {
	value, _ := feature["truncated"].(string)
	return value != ""
}

type gffAttr struct {
	Key    string
	Value  string
	Values []string
}

func gffAttrString(attrs []gffAttr) string {
	out := make([]string, 0, len(attrs))
	for _, attr := range attrs {
		if attr.Key == "" {
			continue
		}
		if len(attr.Values) > 0 {
			values := make([]string, 0, len(attr.Values))
			for _, value := range attr.Values {
				if value == "" {
					continue
				}
				values = append(values, gffEscape(value))
			}
			if len(values) == 0 {
				continue
			}
			out = append(out, attr.Key+"="+strings.Join(values, ","))
			continue
		}
		if attr.Value == "" {
			continue
		}
		out = append(out, attr.Key+"="+gffEscape(attr.Value))
	}
	if len(out) == 0 {
		return "."
	}
	return strings.Join(out, ";")
}

func gffEscape(value string) string {
	var buf strings.Builder
	for i := 0; i < len(value); i++ {
		switch value[i] {
		case '\t':
			buf.WriteString("%09")
		case '\n':
			buf.WriteString("%0A")
		case '\r':
			buf.WriteString("%0D")
		case '%':
			buf.WriteString("%25")
		case ';':
			buf.WriteString("%3B")
		case '=':
			buf.WriteString("%3D")
		case '&':
			buf.WriteString("%26")
		case ',':
			buf.WriteString("%2C")
		default:
			buf.WriteByte(value[i])
		}
	}
	return buf.String()
}

func gffNumber(value any) string {
	switch v := value.(type) {
	case nil:
		return "."
	case json.Number:
		return formatGFFFloat(v.String())
	case fmt.Stringer:
		return formatGFFFloat(v.String())
	case string:
		return formatGFFFloat(v)
	case float64:
		return strconv.FormatFloat(v, 'g', -1, 64)
	case int:
		return strconv.Itoa(v)
	case int64:
		return strconv.FormatInt(v, 10)
	default:
		if f, ok := jsonFloat(value); ok {
			return strconv.FormatFloat(f, 'g', -1, 64)
		}
		return "."
	}
}

func formatGFFFloat(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return "."
	}
	f, err := strconv.ParseFloat(value, 64)
	if err != nil {
		return value
	}
	return strconv.FormatFloat(f, 'g', -1, 64)
}

func writeGFF3FASTA(buf *bytes.Buffer, sequences []gffSequence) {
	buf.WriteString("##FASTA\n")
	for _, sequence := range sequences {
		if sequence.ID == "" || sequence.Sequence == "" {
			continue
		}
		fmt.Fprintf(buf, ">%s\n", sequence.ID)
		writeWrappedSequence(buf, sequence.Sequence, 60)
	}
}

func writeWrappedSequence(buf *bytes.Buffer, sequence string, width int) {
	if width <= 0 {
		width = 60
	}
	for len(sequence) > width {
		buf.WriteString(sequence[:width])
		buf.WriteByte('\n')
		sequence = sequence[width:]
	}
	if sequence != "" {
		buf.WriteString(sequence)
		buf.WriteByte('\n')
	}
}

func mapSlice(value any) []map[string]any {
	raw, _ := value.([]any)
	out := make([]map[string]any, 0, len(raw))
	for _, item := range raw {
		obj, ok := item.(map[string]any)
		if ok {
			out = append(out, obj)
		}
	}
	return out
}

func stringSlice(value any) []string {
	raw, _ := value.([]any)
	out := make([]string, 0, len(raw))
	for _, item := range raw {
		str, ok := item.(string)
		if ok {
			out = append(out, str)
		}
	}
	return out
}
