package bakpack

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/martinghunt/bakpack/internal/buildinfo"
)

func TestBaktaGFF3RejectsInvalidSequenceLength(t *testing.T) {
	genome := mustGenome(t, "sample1", toyFASTA("sample1"))
	original := []byte(`{
  "genome": {"translation_table": 11},
  "sequences": [
    {"id": "contig1", "length": -3, "sequence": "ATGAAATAA"}
  ],
  "features": []
}`)
	if _, err := BaktaGFF3(original, genome); err == nil {
		t.Fatal("BaktaGFF3() with negative sequence length = nil error, want error")
	}
}

func TestBaktaGFF3RejectsInvalidFeatureCoordinates(t *testing.T) {
	genome := mustGenome(t, "sample1", toyFASTA("sample1"))
	original := []byte(`{
  "genome": {"translation_table": 11},
  "sequences": [
    {"id": "contig1", "length": 9, "sequence": "ATGAAATAA"}
  ],
  "features": [
    {"type": "cds", "contig": "contig1", "start": 0, "stop": 9, "strand": "+"}
  ]
}`)
	if _, err := BaktaGFF3(original, genome); err == nil {
		t.Fatal("BaktaGFF3() with zero feature start = nil error, want error")
	}
}

func TestBaktaGFF3AllowsWraparoundFeatureCoordinates(t *testing.T) {
	// start > stop is the deliberate convention for a feature that wraps
	// around the origin of a circular contig; it must not be rejected.
	genome := mustGenome(t, "sample1", toyFASTA("sample1"))
	original := []byte(`{
  "genome": {"translation_table": 11},
  "sequences": [
    {"id": "contig1", "length": 9, "sequence": "ATGAAATAA"}
  ],
  "features": [
    {"type": "gap", "contig": "contig1", "start": 8, "stop": 2, "length": 4}
  ]
}`)
	if _, err := BaktaGFF3(original, genome); err != nil {
		t.Fatalf("BaktaGFF3() with wraparound coordinates error = %v, want nil", err)
	}
}

func TestGFFFeatureIDFallsBackToDistinctValuesWithoutLocusOrID(t *testing.T) {
	featureA := map[string]any{"type": "gap", "contig": "contig1", "start": 1, "stop": 4}
	featureB := map[string]any{"type": "gap", "contig": "contig1", "start": 5, "stop": 9}

	idA := gffFeatureID(featureA)
	idB := gffFeatureID(featureB)

	if idA == "." || idB == "." {
		t.Fatalf("gffFeatureID() = %q, %q, want no fallback to the ambiguous constant \".\"", idA, idB)
	}
	if idA == idB {
		t.Fatalf("gffFeatureID() returned the same ID %q for two different features", idA)
	}
}

func TestBaktaGFF3FromOriginalAndReducedJSON(t *testing.T) {
	genome := mustGenome(t, "sample1", toyFASTA("sample1"))
	original := toyBaktaJSON("sample1", "gene one")
	want := []byte(strings.Join([]string{
		"##gff-version 3",
		"##feature-ontology https://github.com/The-Sequence-Ontology/SO-Ontologies/blob/v3.1/so.obo",
		"# Generated by bakpack " + buildinfo.Version,
		"# Annotated with Bakta",
		"# DOI: 10.1099/mgen.0.000685",
		"# URL: github.com/oschwengers/bakta",
		"##sequence-region contig1 1 9",
		"contig1\tBakta\tregion\t1\t9\t.\t+\t.\tID=contig1;Name=contig1",
		"contig1\tPyrodigal\tCDS\t1\t9\t.\t+\t0\tID=toy_00001;Name=gene one;product=gene one",
		"##FASTA",
		">contig1",
		"ATGAAATAA",
		"",
	}, "\n"))

	got, err := BaktaGFF3(original, genome)
	if err != nil {
		t.Fatalf("BaktaGFF3(original) error = %v", err)
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("BaktaGFF3(original) =\n%s\nwant\n%s", got, want)
	}

	reduced, err := ReduceBaktaJSON(original, genome)
	if err != nil {
		t.Fatal(err)
	}
	got, err = BaktaGFF3(reduced.ReducedJSON, genome)
	if err != nil {
		t.Fatalf("BaktaGFF3(reduced) error = %v", err)
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("BaktaGFF3(reduced) =\n%s\nwant\n%s", got, want)
	}

	wantAnnotationOnly := []byte(strings.Join([]string{
		"##gff-version 3",
		"##feature-ontology https://github.com/The-Sequence-Ontology/SO-Ontologies/blob/v3.1/so.obo",
		"# Generated by bakpack " + buildinfo.Version,
		"# Annotated with Bakta",
		"# DOI: 10.1099/mgen.0.000685",
		"# URL: github.com/oschwengers/bakta",
		"##sequence-region contig1 1 9",
		"contig1\tBakta\tregion\t1\t9\t.\t+\t.\tID=contig1;Name=contig1",
		"contig1\tPyrodigal\tCDS\t1\t9\t.\t+\t0\tID=toy_00001;Name=gene one;product=gene one",
		"",
	}, "\n"))
	got, err = BaktaGFF3WithOptions(reduced.ReducedJSON, genome, BaktaGFF3Options{AnnotationOnly: true})
	if err != nil {
		t.Fatalf("BaktaGFF3WithOptions(reduced, AnnotationOnly) error = %v", err)
	}
	if !bytes.Equal(got, wantAnnotationOnly) {
		t.Fatalf("BaktaGFF3WithOptions(reduced, AnnotationOnly) =\n%s\nwant\n%s", got, wantAnnotationOnly)
	}

	got, err = BaktaGFF3WithOptions(original, genome, BaktaGFF3Options{BakpackVersion: "v9.8.7"})
	if err != nil {
		t.Fatalf("BaktaGFF3WithOptions(original, BakpackVersion) error = %v", err)
	}
	if !bytes.Contains(got, []byte("# Generated by bakpack v9.8.7\n")) {
		t.Fatalf("BaktaGFF3WithOptions(original, BakpackVersion) missing version override: %s", got)
	}
}

func TestBaktaGFF3MatchesProvidedBaktaOutput(t *testing.T) {
	base := "/Users/mh46/Work/Compress_bakta"
	annotationDir := filepath.Join(base, "atb.bakta.r0.2.batch.10")
	matches, err := filepath.Glob(filepath.Join(annotationDir, "*.bakta.json"))
	if err != nil {
		t.Fatal(err)
	}
	if len(matches) == 0 {
		t.Skipf("local Bakta parity fixtures not available under %s", annotationDir)
	}
	for _, annotationPath := range matches {
		sample := strings.TrimSuffix(filepath.Base(annotationPath), ".bakta.json")
		t.Run(sample, func(t *testing.T) {
			genomePath := filepath.Join(base, "atb.assembly.r0.2.batch.10", sample+".fa")
			gff3Path := filepath.Join(base, "atb.bakta.r0.2.batch.10.gff3_files", sample+".gff3")
			for _, path := range []string{genomePath, gff3Path} {
				if _, err := os.Stat(path); err != nil {
					t.Skipf("local Bakta parity fixture not available: %s", path)
				}
			}
			annotation, err := os.ReadFile(annotationPath)
			if err != nil {
				t.Fatal(err)
			}
			genomeBytes, err := os.ReadFile(genomePath)
			if err != nil {
				t.Fatal(err)
			}
			want, err := os.ReadFile(gff3Path)
			if err != nil {
				t.Fatal(err)
			}
			genome, err := ReadGenome(sample, sample+".fa", genomeBytes)
			if err != nil {
				t.Fatal(err)
			}
			got, err := BaktaGFF3(annotation, genome)
			if err != nil {
				t.Fatalf("BaktaGFF3() error = %v", err)
			}
			gotWithoutBakpackHeader := stripBakpackGFF3Header(got)
			if !bytes.Equal(gotWithoutBakpackHeader, want) {
				t.Fatalf("BaktaGFF3() differs from Bakta GFF3 fixture after stripping bakpack header: %s", firstDiff(gotWithoutBakpackHeader, want))
			}
		})
	}
}

func TestBaktaGFF3FeatureTypesCoverValidationIndexes(t *testing.T) {
	roots := []string{
		"/Users/mh46/Work/Compress_bakta/incr_202408_bakpack_validation_v9_10",
		"/Users/mh46/Work/Compress_bakta/incr_202408_bakpack_validation_v9_10_remote",
	}
	var indexPaths []string
	for _, root := range roots {
		matches, err := filepath.Glob(filepath.Join(root, "work", "batch_*", "index.json"))
		if err != nil {
			t.Fatal(err)
		}
		indexPaths = append(indexPaths, matches...)
	}
	if len(indexPaths) == 0 {
		t.Skip("local bakpack validation indexes not available")
	}

	observed := map[string]bool{}
	unsupported := map[string][]string{}
	totalSamples := 0
	for _, path := range indexPaths {
		data, err := os.ReadFile(path)
		if err != nil {
			t.Fatal(err)
		}
		root, err := DecodeJSON(data)
		if err != nil {
			t.Fatal(err)
		}
		if obj, ok := root.(map[string]any); ok {
			totalSamples += len(mapSlice(obj["samples"]))
		}
		walkIndexTypeValues(root, func(featureType string) {
			observed[featureType] = true
			if !gffFeatureTypeSupported(featureType) {
				unsupported[featureType] = append(unsupported[featureType], path)
			}
		})
	}
	if len(observed) == 0 {
		t.Fatalf("no feature type values found in %d validation indexes", len(indexPaths))
	}
	if len(unsupported) != 0 {
		t.Fatalf("validation indexes contain unsupported GFF3 feature types across %d samples: %#v", totalSamples, unsupported)
	}
}

func TestSupportedBaktaFeatureTypes(t *testing.T) {
	want := []string{"cds", "crispr", "gap", "ncRNA", "ncRNA-region", "oriC", "oriT", "rRNA", "sorf", "tRNA", "tmRNA"}
	got := SupportedBaktaFeatureTypes()
	if !slices.Equal(got, want) {
		t.Fatalf("SupportedBaktaFeatureTypes() = %#v, want %#v", got, want)
	}
}

func TestBaktaGFF3ErrorsOnUnsupportedFeatureType(t *testing.T) {
	genome := mustGenome(t, "sample1", toyFASTA("sample1"))
	annotation := bytes.Replace(toyBaktaJSON("sample1", "gene one"), []byte(`"type": "cds"`), []byte(`"type": "new-feature"`), 1)

	_, err := BaktaGFF3(annotation, genome)
	if err == nil || !strings.Contains(err.Error(), `unsupported Bakta feature type "new-feature"`) {
		t.Fatalf("BaktaGFF3() error = %v, want unsupported feature type error", err)
	}
}

func firstDiff(got, want []byte) string {
	limit := len(got)
	if len(want) < limit {
		limit = len(want)
	}
	for i := 0; i < limit; i++ {
		if got[i] != want[i] {
			return fmt.Sprintf("offset %d got %q want %q", i, got[i], want[i])
		}
	}
	return fmt.Sprintf("length got %d want %d", len(got), len(want))
}

func stripBakpackGFF3Header(data []byte) []byte {
	line := []byte("# Generated by bakpack " + buildinfo.Version + "\n")
	return bytes.Replace(data, line, nil, 1)
}

func gffFeatureTypeSupported(featureType string) bool {
	return isSupportedBaktaFeatureType(featureType)
}

func walkIndexTypeValues(value any, fn func(string)) {
	switch v := value.(type) {
	case map[string]any:
		if field, _ := v["field"].(string); field == "type" {
			for _, item := range stringSlice(v["values"]) {
				fn(item)
			}
		}
		for _, child := range v {
			walkIndexTypeValues(child, fn)
		}
	case []any:
		for _, child := range v {
			walkIndexTypeValues(child, fn)
		}
	}
}
